# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Hi, I am Akash.
# Description of the Site
description: Cloud Engineer
# URL of Image of the Site
site-image: /assets/images/logo.png
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: /assets/images/favicon.ico

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/hero-bg.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: akashwh7@gmail.com
facebook_username: 
twitter_username:
linkedin_username: akashwh7 
instagram_username: akashwh7
github_username:  akashwh7
youtube_channel_id: 
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 
telegram_username: akashwh7  

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: 

# Name of the Author
author-name: Akash Mehta
# URL for the Image of the Author
author-image: /assets/images/akash-passport-size-photo.jpg
# 60 Words About the Author
author-about: I'm a cloud engineer who likes to solve problems, and learn new things. Specifically very much in love with Linux, cloud and web technology. Working as a Cloud Engineer in Deloitte. I love travelling, trekking and gaming.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: akashwh7.github.io

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
